/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frame;

import java.awt.Frame;

/**
 *
 * @author Family
 */
public class passcode extends javax.swing.JFrame {

    
    core.Config config = new core.Config();
    core.Repo repo = new core.Repo();
    
    private String passcode = "";
    
    public passcode() {
        initComponents();
        setExtendedState(Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        P1 = new javax.swing.JPasswordField();
        P2 = new javax.swing.JPasswordField();
        P3 = new javax.swing.JPasswordField();
        P4 = new javax.swing.JPasswordField();
        SHOW = new javax.swing.JButton();
        HOME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Enter Password | ABPS Elections");
        setIconImage(new javax.swing.ImageIcon("src/assets/logo.jpg").getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABPS Elections 2018 - 19");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Enter Passcode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        P1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        P1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                P1KeyReleased(evt);
            }
        });

        P2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        P2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                P2KeyReleased(evt);
            }
        });

        P3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        P3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                P3KeyReleased(evt);
            }
        });

        P4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        P4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                P4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(P2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(P3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(P4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(P2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(P3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(P4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        SHOW.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SHOW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/getin.png"))); // NOI18N
        SHOW.setText("Show Results");
        SHOW.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SHOW.setContentAreaFilled(false);
        SHOW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWActionPerformed(evt);
            }
        });

        HOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        HOME.setToolTipText("Go Back");
        HOME.setBorderPainted(false);
        HOME.setContentAreaFilled(false);
        HOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HOME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HOME))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
frame.main main = new frame.main("6th A", true);
this.dispose();
main.setVisible(true);
    }//GEN-LAST:event_HOMEActionPerformed

    private void P1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_P1KeyReleased
String p1 = P1.getText();
if (p1.replaceAll("\\s", "").length() == 1){
    
    this.passcode = this.passcode + p1;
    P2.requestFocus();
    
} else if (p1.replaceAll("\\s", "").length() > 1) {
    
    P1.setText(null);
    P1.requestFocus();
    
}
    }//GEN-LAST:event_P1KeyReleased

    private void P2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_P2KeyReleased
String p2 = P2.getText();
if (p2.replaceAll("\\s", "").length() == 1){
    
    this.passcode = this.passcode + p2;
    P3.requestFocus();
    
} else if (p2.replaceAll("\\s", "").length() > 1) {
    
    P2.setText(null);
    P2.requestFocus();
    
}
    }//GEN-LAST:event_P2KeyReleased

    private void P3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_P3KeyReleased
String p3 = P3.getText();
if (p3.replaceAll("\\s", "").length() == 1){
    
    this.passcode = this.passcode + p3;
    P4.requestFocus();
    
} else if (p3.replaceAll("\\s", "").length() > 1) {
    
    P3.setText(null);
    P3.requestFocus();
    
}
    }//GEN-LAST:event_P3KeyReleased

    private void P4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_P4KeyReleased
String p4 = P4.getText();
if (p4.replaceAll("\\s", "").length() == 1){
    
    this.passcode = this.passcode + p4;
    SHOW.requestFocus();
    
} else if (p4.replaceAll("\\s", "").length() > 1) {
    
    P4.setText(null);
    P4.requestFocus();
    
}
    }//GEN-LAST:event_P4KeyReleased

    private void SHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWActionPerformed
if ((this.passcode).equals(config.passcode)){
    
    frame.results results = new frame.results();
    this.dispose();
    results.setVisible(true);
    
} else {
    
    repo.message("Wrong Passcode", "Wrong Passcode Entered. Please Check.", "ERROR");
    this.passcode = "";
    P1.setText(null);
    P2.setText(null);
    P3.setText(null);
    P4.setText(null);
    P1.requestFocus();
}
    }//GEN-LAST:event_SHOWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passcode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passcode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HOME;
    private javax.swing.JPasswordField P1;
    private javax.swing.JPasswordField P2;
    private javax.swing.JPasswordField P3;
    private javax.swing.JPasswordField P4;
    private javax.swing.JButton SHOW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
